### ISSUE TITLE
Error with Airflow Cmd Forwarding

### ISSUE THREAD

**Issue by anthonysocks** [kaxil/airflowctl#21]
[I suspect that this line](https://github.com/kaxil/airflowctl/blob/5c177a066fb48b4273fb077d9fe79c5e9ed7a942/airflowctl/cli.py#L254) is raising an exception where none should be raised. The error I get is: `Key 'venv_path' not found in settings file`. But I believe the `venv_path` is optional and should fall back on `None` if the project hasn't configured one (if I understand the code correctly).

**Comment by kaxil** [comment]
Could you give me the commands to reproduce it

**Comment by anthonysocks** [comment]
Sorry, I should have included them before:
```
airflowctl init my_project
airflowclt start my_project
```

**Comment by kaxil** [comment]
Cool, thanks, I can reproduce it, will fix it and release a new version in few minutes

**Comment by kaxil** [comment]
I cut 0.2.9 but the thing that you are missing is the `build` command, and if you want to use existing account, pass `--venv-path` to the `init` command or update `settings.yaml` as below:

```yaml
# Path to a virtual environment to be used for the project
mode:
  virtualenv:
    venv_path: "PROJECT_DIR/.venv"
```
